#tomcat
server:
  tomcat:
    uri-encoding: utf-8
#log
#mybatis
mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    root: info
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  http:
    multipart:
      max-file-size: 10MB
aliyun:
  oss:
    accessKey: LTAIfKWKYNEF1ipI
    accessKeySecret: qYTIS76T9GHcoqCzUI2NRr8uIFlix8
    bucketName: yukongaaa-img-upload
    endPoint: oss-cn-shanghai.aliyuncs.com





